associados/urls.py
from django.urls import path
from associados.views import associados,login,cadastro

urlpatterns = [
    path('associados', associados ,name='associados'),
    path('cadastro', cadastro ,name='cadastro'),
    path('login', login ,name='login')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('noticias.urls')),
    path('',include('associados.urls'),name="cadassociados")
]

associados/models.py
from django.db import models

# Create your models here.

associados/forms.py
from django import forms


class AssociadoForms(forms.Form):
    
    GENERO_CHOICE=(
        ('M','Masculino'),
        ('F','Feminino'),
        ('O','Outros'),
        ('PN','Prefiro não responder')
    )
    
    nome_completo = forms.CharField(
        label='Nome Completo',
        required=True,
        max_length=100
    )
    
    nome_social = forms.CharField(
        label='Nome Social',
        required=True,
        max_length=100
    )
    
    email = forms.EmailField(
        label="E-mail",
        required=True,
        max_length=100,
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'placeholder': 'Digite seu e-mail'})
    )
    
    rg = forms.CharField(
        label="RG",
        required=True,
        max_length=7,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Digite seu RG'})
    )
    
    
    genero= forms.ChoiceField(
        label='Por favor informe o seu gênero',
        choices=GENERO_CHOICE,
        widget=forms.Select(attrs={'class': 'form-control','placeholder': 'Identifique sua identidade'}),
        required=True  # Permitir que a pessoa não declare, embora haja 'Prefiro Não Declarar'
    )
    
    genero_outro = forms.CharField(
        label='Selecione "Outro" acima e especifique',
        max_length=100,
        required=True,
        help_text='Use apenas se a opção "Outro" tiver sido selecionada.'
    )
     
    senha_1 = forms.CharField(
        label='Senha',
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                'placeholder': 'Digite sua senha'}
        ),
    )
    senha_2 = forms.CharField(
        label='Senha',
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
        attrs={
                'class': 'form-control',
                'placeholder': 'Digite sua senha novamente',   }
        )
    )
    




class LoginForm(forms.Form):

    nome_login = forms.CharField(
        label='Nome de Login',
        required=True,
        max_length=100
    )
    senha = forms.CharField(
        label='Senha',
        required=True,
        max_length=70,
    widget = forms.PasswordInput()
    )

associados/views.py
from django.shortcuts import render, redirect
from associados.forms import AssociadoForms, LoginForm
from django.contrib.auth.models import User


def associados(request):
    return render(request, 'associados/index.html')

def login(request):
    form = LoginForm()
    return render(request, 'associados/login.html', {'form': form})

def cadastro(request):
    form = AssociadoForms()
    if request.method == 'POST':
        form = AssociadoForms(request.POST)
        if form['senha_1'].value() != form['senha_2'].value():
            return redirect('cadastro')
        
        nome_completo = form['nome_completo'].value()
        nome_social = form['nome_social'].value()
        genero = form['genero'].value()
        email = form['email'].value()
        senha = form['senha_1'].value()
        
        if User.objects.filter(username=nome_completo).exists():
            return redirect('cadastro')
        
        associado = User.objects.create_user(
            username = nome_completo,
            email = email,
            password=senha
            )
        associado.save()
        
        return redirect('login')
        
    return render(request, 'associados/cadastro.html',{'form': form})

templates/associados/cadastro.html
{% extends 'noticias/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-primary">Cadastro de Associado</h2>
        <form action="{% url 'cadastro' %}" method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_nome_completo" class="form-label text-secondary">Nome Completo</label>
                {{ form.nome_completo }}
            </div>

            <div class="mb-3">
                <label for="id_nome_social" class="form-label text-secondary">Nome Social</label>
                {{ form.nome_social }}
            </div>

            <div class="row mb-3">
                <div class="col-md-6">
                    <label class="form-label text-secondary" for="id_cpf">CPF</label>
                    <input type="text" name="cpf" id="id_cpf" class="form-control" placeholder="XXX.XXX.XXX-XX" required>
                </div>

                <div class="col-md-6">
                    <label class="form-label text-secondary" for="id_rg">RG</label>
                    <input type="text" name="rg" id="id_rg" class="form-control" placeholder="Digite seu RG" required>
                </div>
            </div>

            <div class="mb-3">
                <label class="form-label text-secondary" for="id_email">E-mail</label>
                <input type="email" name="email" id="id_email" class="form-control" placeholder="email@example.com" value="{{ email }}" required>
            </div>

            <div class="row mb-3">
                <div class="col-md-6">
                    <label for="id_identidade_genero" class="form-label text-secondary">Qual sua identidade de gênero?</label>
                    {{ form.genero }}
                </div>

                <div class="col-md-6">
                    <label class="form-label text-secondary" for="id_data_nascimento">Data de Nascimento</label>
                    <input type="date" name="data_nascimento" id="id_data_nascimento" class="form-control" required>
                </div>
            </div>

            <div class="mb-3" id="outro-genero-div" style="display:none;">
                <label for="id_genero_outro" class="form-label text-secondary">Especifique outro gênero</label>
                {{ form.genero_outro }}
            </div>

            <div>
                <div class="mb-3">
                    <label for="senha" class="form-label text-secondary">Senha</label>
                    {{ form.senha_1 }}
                </div>

                <div class="mb-3">
                    <label for="senha" class="form-label text-secondary">Confirme a senha</label>
                    {{ form.senha_2 }}
                </div>
            </div>

            <button type="submit" class="btn btn-info mb-4">Cadastrar</button>
        </form>
    </div>

    <script>
        // Mostrar ou esconder o campo de "Outro" baseado na seleção de gênero
        const identidadeGeneroSelect = document.getElementById('id_genero');
        const outroGeneroDiv = document.getElementById('outro-genero-div');

        identidadeGeneroSelect.addEventListener('change', function() {
            if (this.value === 'O') { // Supondo que 'O' seja a opção para "Outro"
                outroGeneroDiv.style.display = 'block';
            } else {
                outroGeneroDiv.style.display = 'none';
            }
        });
    </script>
{% endblock %}

templates/associados/index.html
{% extends 'noticias/base.html'}
{% load static}
{% block content}
    <h4>Cadastro de Associado</h4>
    <form>
        CPF <input type="text" name="cpf">
        RG <input type="text" name="rg">
        Nome Completo <input type="text" name="nome">
        Nome Completo <input type="text" name="nome_social">
        Genero
        <select>
            <option>Masculino</option>
            <option>Feminino</option>
            <option>Outros</option>
            <option>Prefiro não responder</option>
        </select>
        Data Nascimento
        <input type="date" name="dt_nasc">
        <input type="submit" value="cadastrar">

    </form>
{% endblock %}

templates/associados/login.html
{% extends 'noticias/base.html' %}
{% load static %}

{% block content %}
     <div class="container mt-5">
        <h2 class="text-primary">Login</h2>
        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_nome_completo" class="form-label">Nome de usuário</label>
                {{ form.nome_completo }}
            </div>
            
            <div class="mb-3">
                <label for="id_senha" class="form-label">Senha</label>
                {{ form.senha }}
            </div>
            
            <button type="submit" class="btn btn-primary">Entrar</button>
            
            <div class="mt-3">
                <p>Não tem uma conta? <a href="{% url 'cadastro' %}">Cadastre-se aqui</a></p>
            </div>
        </form>
    </div>
{% endblock %}